package main

import "time"

type PayloadSecret struct {
	Action string `json:"action"`
	Alert  struct {
		Number                   int       `json:"number"`
		SecretType               string    `json:"secret_type"`
		URL                      string    `json:"url"`
		HTMLURL                  string    `json:"html_url"`
		LocationsURL             string    `json:"locations_url"`
		CreatedAt                time.Time `json:"created_at"`
		UpdatedAt                time.Time `json:"updated_at"`
		Validity                 string    `json:"validity"`
		Resolution               any       `json:"resolution"`
		ResolvedBy               any       `json:"resolved_by"`
		ResolvedAt               any       `json:"resolved_at"`
		ResolutionComment        any       `json:"resolution_comment"`
		PushProtectionBypassed   bool      `json:"push_protection_bypassed"`
		PushProtectionBypassedBy any       `json:"push_protection_bypassed_by"`
		PushProtectionBypassedAt any       `json:"push_protection_bypassed_at"`
	} `json:"alert"`
	Repository struct {
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		Name     string `json:"name"`
		FullName string `json:"full_name"`
		Private  bool   `json:"private"`
		Owner    struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"owner"`
		HTMLURL                  string    `json:"html_url"`
		Description              any       `json:"description"`
		Fork                     bool      `json:"fork"`
		URL                      string    `json:"url"`
		ForksURL                 string    `json:"forks_url"`
		KeysURL                  string    `json:"keys_url"`
		CollaboratorsURL         string    `json:"collaborators_url"`
		TeamsURL                 string    `json:"teams_url"`
		HooksURL                 string    `json:"hooks_url"`
		IssueEventsURL           string    `json:"issue_events_url"`
		EventsURL                string    `json:"events_url"`
		AssigneesURL             string    `json:"assignees_url"`
		BranchesURL              string    `json:"branches_url"`
		TagsURL                  string    `json:"tags_url"`
		BlobsURL                 string    `json:"blobs_url"`
		GitTagsURL               string    `json:"git_tags_url"`
		GitRefsURL               string    `json:"git_refs_url"`
		TreesURL                 string    `json:"trees_url"`
		StatusesURL              string    `json:"statuses_url"`
		LanguagesURL             string    `json:"languages_url"`
		StargazersURL            string    `json:"stargazers_url"`
		ContributorsURL          string    `json:"contributors_url"`
		SubscribersURL           string    `json:"subscribers_url"`
		SubscriptionURL          string    `json:"subscription_url"`
		CommitsURL               string    `json:"commits_url"`
		GitCommitsURL            string    `json:"git_commits_url"`
		CommentsURL              string    `json:"comments_url"`
		IssueCommentURL          string    `json:"issue_comment_url"`
		ContentsURL              string    `json:"contents_url"`
		CompareURL               string    `json:"compare_url"`
		MergesURL                string    `json:"merges_url"`
		ArchiveURL               string    `json:"archive_url"`
		DownloadsURL             string    `json:"downloads_url"`
		IssuesURL                string    `json:"issues_url"`
		PullsURL                 string    `json:"pulls_url"`
		MilestonesURL            string    `json:"milestones_url"`
		NotificationsURL         string    `json:"notifications_url"`
		LabelsURL                string    `json:"labels_url"`
		ReleasesURL              string    `json:"releases_url"`
		DeploymentsURL           string    `json:"deployments_url"`
		CreatedAt                time.Time `json:"created_at"`
		UpdatedAt                time.Time `json:"updated_at"`
		PushedAt                 time.Time `json:"pushed_at"`
		GitURL                   string    `json:"git_url"`
		SSHURL                   string    `json:"ssh_url"`
		CloneURL                 string    `json:"clone_url"`
		SvnURL                   string    `json:"svn_url"`
		Homepage                 any       `json:"homepage"`
		Size                     int       `json:"size"`
		StargazersCount          int       `json:"stargazers_count"`
		WatchersCount            int       `json:"watchers_count"`
		Language                 string    `json:"language"`
		HasIssues                bool      `json:"has_issues"`
		HasProjects              bool      `json:"has_projects"`
		HasDownloads             bool      `json:"has_downloads"`
		HasWiki                  bool      `json:"has_wiki"`
		HasPages                 bool      `json:"has_pages"`
		HasDiscussions           bool      `json:"has_discussions"`
		ForksCount               int       `json:"forks_count"`
		MirrorURL                any       `json:"mirror_url"`
		Archived                 bool      `json:"archived"`
		Disabled                 bool      `json:"disabled"`
		OpenIssuesCount          int       `json:"open_issues_count"`
		License                  any       `json:"license"`
		AllowForking             bool      `json:"allow_forking"`
		IsTemplate               bool      `json:"is_template"`
		WebCommitSignoffRequired bool      `json:"web_commit_signoff_required"`
		Topics                   []any     `json:"topics"`
		Visibility               string    `json:"visibility"`
		Forks                    int       `json:"forks"`
		OpenIssues               int       `json:"open_issues"`
		Watchers                 int       `json:"watchers"`
		DefaultBranch            string    `json:"default_branch"`
		CustomProperties         struct {
		} `json:"custom_properties"`
	} `json:"repository"`
	Organization struct {
		Login            string `json:"login"`
		ID               int    `json:"id"`
		NodeID           string `json:"node_id"`
		URL              string `json:"url"`
		ReposURL         string `json:"repos_url"`
		EventsURL        string `json:"events_url"`
		HooksURL         string `json:"hooks_url"`
		IssuesURL        string `json:"issues_url"`
		MembersURL       string `json:"members_url"`
		PublicMembersURL string `json:"public_members_url"`
		AvatarURL        string `json:"avatar_url"`
		Description      string `json:"description"`
	} `json:"organization"`
	Enterprise struct {
		ID          int       `json:"id"`
		Slug        string    `json:"slug"`
		Name        string    `json:"name"`
		NodeID      string    `json:"node_id"`
		AvatarURL   string    `json:"avatar_url"`
		Description string    `json:"description"`
		WebsiteURL  string    `json:"website_url"`
		HTMLURL     string    `json:"html_url"`
		CreatedAt   time.Time `json:"created_at"`
		UpdatedAt   time.Time `json:"updated_at"`
	} `json:"enterprise"`
	Sender struct {
		Login             string `json:"login"`
		ID                int    `json:"id"`
		NodeID            string `json:"node_id"`
		AvatarURL         string `json:"avatar_url"`
		GravatarID        string `json:"gravatar_id"`
		URL               string `json:"url"`
		HTMLURL           string `json:"html_url"`
		FollowersURL      string `json:"followers_url"`
		FollowingURL      string `json:"following_url"`
		GistsURL          string `json:"gists_url"`
		StarredURL        string `json:"starred_url"`
		SubscriptionsURL  string `json:"subscriptions_url"`
		OrganizationsURL  string `json:"organizations_url"`
		ReposURL          string `json:"repos_url"`
		EventsURL         string `json:"events_url"`
		ReceivedEventsURL string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"sender"`
}

type PayloadCode struct {
	Action string `json:"action"`
	Alert  struct {
		Number           int         `json:"number"`
		CreatedAt        time.Time   `json:"created_at"`
		UpdatedAt        time.Time   `json:"updated_at"`
		URL              string      `json:"url"`
		HTMLURL          string      `json:"html_url"`
		State            string      `json:"state"`
		FixedAt          interface{} `json:"fixed_at"`
		DismissedBy      interface{} `json:"dismissed_by"`
		DismissedAt      interface{} `json:"dismissed_at"`
		DismissedReason  interface{} `json:"dismissed_reason"`
		DismissedComment interface{} `json:"dismissed_comment"`
		Rule             struct {
			ID                    string   `json:"id"`
			Severity              string   `json:"severity"`
			Description           string   `json:"description"`
			Name                  string   `json:"name"`
			Tags                  []string `json:"tags"`
			FullDescription       string   `json:"full_description"`
			Help                  string   `json:"help"`
			SecuritySeverityLevel string   `json:"security_severity_level"`
		} `json:"rule"`
		Tool struct {
			Name    string      `json:"name"`
			GUID    interface{} `json:"guid"`
			Version string      `json:"version"`
		} `json:"tool"`
		MostRecentInstance struct {
			Ref         string `json:"ref"`
			AnalysisKey string `json:"analysis_key"`
			Environment string `json:"environment"`
			Category    string `json:"category"`
			State       string `json:"state"`
			CommitSha   string `json:"commit_sha"`
			Message     struct {
				Text string `json:"text"`
			} `json:"message"`
			Location struct {
				Path        string `json:"path"`
				StartLine   int    `json:"start_line"`
				EndLine     int    `json:"end_line"`
				StartColumn int    `json:"start_column"`
				EndColumn   int    `json:"end_column"`
			} `json:"location"`
			Classifications []interface{} `json:"classifications"`
		} `json:"most_recent_instance"`
		InstancesURL string `json:"instances_url"`
	} `json:"alert"`
	Ref        string `json:"ref"`
	CommitOid  string `json:"commit_oid"`
	Repository struct {
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		Name     string `json:"name"`
		FullName string `json:"full_name"`
		Private  bool   `json:"private"`
		Owner    struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"owner"`
		HTMLURL          string      `json:"html_url"`
		Description      interface{} `json:"description"`
		Fork             bool        `json:"fork"`
		URL              string      `json:"url"`
		ForksURL         string      `json:"forks_url"`
		KeysURL          string      `json:"keys_url"`
		CollaboratorsURL string      `json:"collaborators_url"`
		TeamsURL         string      `json:"teams_url"`
		HooksURL         string      `json:"hooks_url"`
		IssueEventsURL   string      `json:"issue_events_url"`
		EventsURL        string      `json:"events_url"`
		AssigneesURL     string      `json:"assignees_url"`
		BranchesURL      string      `json:"branches_url"`
		TagsURL          string      `json:"tags_url"`
		BlobsURL         string      `json:"blobs_url"`
		GitTagsURL       string      `json:"git_tags_url"`
		GitRefsURL       string      `json:"git_refs_url"`
		TreesURL         string      `json:"trees_url"`
		StatusesURL      string      `json:"statuses_url"`
		LanguagesURL     string      `json:"languages_url"`
		StargazersURL    string      `json:"stargazers_url"`
		ContributorsURL  string      `json:"contributors_url"`
		SubscribersURL   string      `json:"subscribers_url"`
		SubscriptionURL  string      `json:"subscription_url"`
		CommitsURL       string      `json:"commits_url"`
		GitCommitsURL    string      `json:"git_commits_url"`
		CommentsURL      string      `json:"comments_url"`
		IssueCommentURL  string      `json:"issue_comment_url"`
		ContentsURL      string      `json:"contents_url"`
		CompareURL       string      `json:"compare_url"`
		MergesURL        string      `json:"merges_url"`
		ArchiveURL       string      `json:"archive_url"`
		DownloadsURL     string      `json:"downloads_url"`
		IssuesURL        string      `json:"issues_url"`
		PullsURL         string      `json:"pulls_url"`
		MilestonesURL    string      `json:"milestones_url"`
		NotificationsURL string      `json:"notifications_url"`
		LabelsURL        string      `json:"labels_url"`
		ReleasesURL      string      `json:"releases_url"`
		DeploymentsURL   string      `json:"deployments_url"`
		CreatedAt        time.Time   `json:"created_at"`
		UpdatedAt        time.Time   `json:"updated_at"`
		PushedAt         time.Time   `json:"pushed_at"`
		GitURL           string      `json:"git_url"`
		SSHURL           string      `json:"ssh_url"`
		CloneURL         string      `json:"clone_url"`
		SvnURL           string      `json:"svn_url"`
		Homepage         interface{} `json:"homepage"`
		Size             int         `json:"size"`
		StargazersCount  int         `json:"stargazers_count"`
		WatchersCount    int         `json:"watchers_count"`
		Language         string      `json:"language"`
		HasIssues        bool        `json:"has_issues"`
		HasProjects      bool        `json:"has_projects"`
		HasDownloads     bool        `json:"has_downloads"`
		HasWiki          bool        `json:"has_wiki"`
		HasPages         bool        `json:"has_pages"`
		HasDiscussions   bool        `json:"has_discussions"`
		ForksCount       int         `json:"forks_count"`
		MirrorURL        interface{} `json:"mirror_url"`
		Archived         bool        `json:"archived"`
		Disabled         bool        `json:"disabled"`
		OpenIssuesCount  int         `json:"open_issues_count"`
		License          struct {
			Key    string      `json:"key"`
			Name   string      `json:"name"`
			SpdxID string      `json:"spdx_id"`
			URL    interface{} `json:"url"`
			NodeID string      `json:"node_id"`
		} `json:"license"`
		AllowForking             bool          `json:"allow_forking"`
		IsTemplate               bool          `json:"is_template"`
		WebCommitSignoffRequired bool          `json:"web_commit_signoff_required"`
		Topics                   []interface{} `json:"topics"`
		Visibility               string        `json:"visibility"`
		Forks                    int           `json:"forks"`
		OpenIssues               int           `json:"open_issues"`
		Watchers                 int           `json:"watchers"`
		DefaultBranch            string        `json:"default_branch"`
		CustomProperties         struct {
		} `json:"custom_properties"`
	} `json:"repository"`
	Organization struct {
		Login            string `json:"login"`
		ID               int    `json:"id"`
		NodeID           string `json:"node_id"`
		URL              string `json:"url"`
		ReposURL         string `json:"repos_url"`
		EventsURL        string `json:"events_url"`
		HooksURL         string `json:"hooks_url"`
		IssuesURL        string `json:"issues_url"`
		MembersURL       string `json:"members_url"`
		PublicMembersURL string `json:"public_members_url"`
		AvatarURL        string `json:"avatar_url"`
		Description      string `json:"description"`
	} `json:"organization"`
	Enterprise struct {
		ID          int       `json:"id"`
		Slug        string    `json:"slug"`
		Name        string    `json:"name"`
		NodeID      string    `json:"node_id"`
		AvatarURL   string    `json:"avatar_url"`
		Description string    `json:"description"`
		WebsiteURL  string    `json:"website_url"`
		HTMLURL     string    `json:"html_url"`
		CreatedAt   time.Time `json:"created_at"`
		UpdatedAt   time.Time `json:"updated_at"`
	} `json:"enterprise"`
	Sender struct {
		Login             string `json:"login"`
		ID                int    `json:"id"`
		NodeID            string `json:"node_id"`
		AvatarURL         string `json:"avatar_url"`
		GravatarID        string `json:"gravatar_id"`
		URL               string `json:"url"`
		HTMLURL           string `json:"html_url"`
		FollowersURL      string `json:"followers_url"`
		FollowingURL      string `json:"following_url"`
		GistsURL          string `json:"gists_url"`
		StarredURL        string `json:"starred_url"`
		SubscriptionsURL  string `json:"subscriptions_url"`
		OrganizationsURL  string `json:"organizations_url"`
		ReposURL          string `json:"repos_url"`
		EventsURL         string `json:"events_url"`
		ReceivedEventsURL string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"sender"`
}

type PayloadDependabot struct {
	Action string `json:"action"`
	Alert  struct {
		Number     int    `json:"number"`
		State      string `json:"state"`
		Dependency struct {
			Package struct {
				Ecosystem string `json:"ecosystem"`
				Name      string `json:"name"`
			} `json:"package"`
			ManifestPath string `json:"manifest_path"`
			Scope        string `json:"scope"`
		} `json:"dependency"`
		SecurityAdvisory struct {
			GhsaID      string `json:"ghsa_id"`
			CveID       string `json:"cve_id"`
			Summary     string `json:"summary"`
			Description string `json:"description"`
			Severity    string `json:"severity"`
			Identifiers []struct {
				Value string `json:"value"`
				Type  string `json:"type"`
			} `json:"identifiers"`
			References []struct {
				URL string `json:"url"`
			} `json:"references"`
			PublishedAt     time.Time `json:"published_at"`
			UpdatedAt       time.Time `json:"updated_at"`
			WithdrawnAt     any       `json:"withdrawn_at"`
			Vulnerabilities []struct {
				Package struct {
					Ecosystem string `json:"ecosystem"`
					Name      string `json:"name"`
				} `json:"package"`
				Severity               string `json:"severity"`
				VulnerableVersionRange string `json:"vulnerable_version_range"`
				FirstPatchedVersion    struct {
					Identifier string `json:"identifier"`
				} `json:"first_patched_version"`
			} `json:"vulnerabilities"`
			Cvss struct {
				VectorString string  `json:"vector_string"`
				Score        float64 `json:"score"`
			} `json:"cvss"`
			Cwes []struct {
				CweID string `json:"cwe_id"`
				Name  string `json:"name"`
			} `json:"cwes"`
		} `json:"security_advisory"`
		SecurityVulnerability struct {
			Package struct {
				Ecosystem string `json:"ecosystem"`
				Name      string `json:"name"`
			} `json:"package"`
			Severity               string `json:"severity"`
			VulnerableVersionRange string `json:"vulnerable_version_range"`
			FirstPatchedVersion    struct {
				Identifier string `json:"identifier"`
			} `json:"first_patched_version"`
		} `json:"security_vulnerability"`
		URL              string    `json:"url"`
		HTMLURL          string    `json:"html_url"`
		CreatedAt        time.Time `json:"created_at"`
		UpdatedAt        time.Time `json:"updated_at"`
		DismissedAt      any       `json:"dismissed_at"`
		DismissedBy      any       `json:"dismissed_by"`
		DismissedReason  any       `json:"dismissed_reason"`
		DismissedComment any       `json:"dismissed_comment"`
		FixedAt          any       `json:"fixed_at"`
		AutoDismissedAt  any       `json:"auto_dismissed_at"`
	} `json:"alert"`
	Repository struct {
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		Name     string `json:"name"`
		FullName string `json:"full_name"`
		Private  bool   `json:"private"`
		Owner    struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"owner"`
		HTMLURL          string    `json:"html_url"`
		Description      any       `json:"description"`
		Fork             bool      `json:"fork"`
		URL              string    `json:"url"`
		ForksURL         string    `json:"forks_url"`
		KeysURL          string    `json:"keys_url"`
		CollaboratorsURL string    `json:"collaborators_url"`
		TeamsURL         string    `json:"teams_url"`
		HooksURL         string    `json:"hooks_url"`
		IssueEventsURL   string    `json:"issue_events_url"`
		EventsURL        string    `json:"events_url"`
		AssigneesURL     string    `json:"assignees_url"`
		BranchesURL      string    `json:"branches_url"`
		TagsURL          string    `json:"tags_url"`
		BlobsURL         string    `json:"blobs_url"`
		GitTagsURL       string    `json:"git_tags_url"`
		GitRefsURL       string    `json:"git_refs_url"`
		TreesURL         string    `json:"trees_url"`
		StatusesURL      string    `json:"statuses_url"`
		LanguagesURL     string    `json:"languages_url"`
		StargazersURL    string    `json:"stargazers_url"`
		ContributorsURL  string    `json:"contributors_url"`
		SubscribersURL   string    `json:"subscribers_url"`
		SubscriptionURL  string    `json:"subscription_url"`
		CommitsURL       string    `json:"commits_url"`
		GitCommitsURL    string    `json:"git_commits_url"`
		CommentsURL      string    `json:"comments_url"`
		IssueCommentURL  string    `json:"issue_comment_url"`
		ContentsURL      string    `json:"contents_url"`
		CompareURL       string    `json:"compare_url"`
		MergesURL        string    `json:"merges_url"`
		ArchiveURL       string    `json:"archive_url"`
		DownloadsURL     string    `json:"downloads_url"`
		IssuesURL        string    `json:"issues_url"`
		PullsURL         string    `json:"pulls_url"`
		MilestonesURL    string    `json:"milestones_url"`
		NotificationsURL string    `json:"notifications_url"`
		LabelsURL        string    `json:"labels_url"`
		ReleasesURL      string    `json:"releases_url"`
		DeploymentsURL   string    `json:"deployments_url"`
		CreatedAt        time.Time `json:"created_at"`
		UpdatedAt        time.Time `json:"updated_at"`
		PushedAt         time.Time `json:"pushed_at"`
		GitURL           string    `json:"git_url"`
		SSHURL           string    `json:"ssh_url"`
		CloneURL         string    `json:"clone_url"`
		SvnURL           string    `json:"svn_url"`
		Homepage         any       `json:"homepage"`
		Size             int       `json:"size"`
		StargazersCount  int       `json:"stargazers_count"`
		WatchersCount    int       `json:"watchers_count"`
		Language         string    `json:"language"`
		HasIssues        bool      `json:"has_issues"`
		HasProjects      bool      `json:"has_projects"`
		HasDownloads     bool      `json:"has_downloads"`
		HasWiki          bool      `json:"has_wiki"`
		HasPages         bool      `json:"has_pages"`
		HasDiscussions   bool      `json:"has_discussions"`
		ForksCount       int       `json:"forks_count"`
		MirrorURL        any       `json:"mirror_url"`
		Archived         bool      `json:"archived"`
		Disabled         bool      `json:"disabled"`
		OpenIssuesCount  int       `json:"open_issues_count"`
		License          struct {
			Key    string `json:"key"`
			Name   string `json:"name"`
			SpdxID string `json:"spdx_id"`
			URL    any    `json:"url"`
			NodeID string `json:"node_id"`
		} `json:"license"`
		AllowForking             bool   `json:"allow_forking"`
		IsTemplate               bool   `json:"is_template"`
		WebCommitSignoffRequired bool   `json:"web_commit_signoff_required"`
		Topics                   []any  `json:"topics"`
		Visibility               string `json:"visibility"`
		Forks                    int    `json:"forks"`
		OpenIssues               int    `json:"open_issues"`
		Watchers                 int    `json:"watchers"`
		DefaultBranch            string `json:"default_branch"`
		CustomProperties         struct {
		} `json:"custom_properties"`
	} `json:"repository"`
	Organization struct {
		Login            string `json:"login"`
		ID               int    `json:"id"`
		NodeID           string `json:"node_id"`
		URL              string `json:"url"`
		ReposURL         string `json:"repos_url"`
		EventsURL        string `json:"events_url"`
		HooksURL         string `json:"hooks_url"`
		IssuesURL        string `json:"issues_url"`
		MembersURL       string `json:"members_url"`
		PublicMembersURL string `json:"public_members_url"`
		AvatarURL        string `json:"avatar_url"`
		Description      string `json:"description"`
	} `json:"organization"`
	Enterprise struct {
		ID          int       `json:"id"`
		Slug        string    `json:"slug"`
		Name        string    `json:"name"`
		NodeID      string    `json:"node_id"`
		AvatarURL   string    `json:"avatar_url"`
		Description string    `json:"description"`
		WebsiteURL  string    `json:"website_url"`
		HTMLURL     string    `json:"html_url"`
		CreatedAt   time.Time `json:"created_at"`
		UpdatedAt   time.Time `json:"updated_at"`
	} `json:"enterprise"`
	Sender struct {
		Login             string `json:"login"`
		ID                int    `json:"id"`
		NodeID            string `json:"node_id"`
		AvatarURL         string `json:"avatar_url"`
		GravatarID        string `json:"gravatar_id"`
		URL               string `json:"url"`
		HTMLURL           string `json:"html_url"`
		FollowersURL      string `json:"followers_url"`
		FollowingURL      string `json:"following_url"`
		GistsURL          string `json:"gists_url"`
		StarredURL        string `json:"starred_url"`
		SubscriptionsURL  string `json:"subscriptions_url"`
		OrganizationsURL  string `json:"organizations_url"`
		ReposURL          string `json:"repos_url"`
		EventsURL         string `json:"events_url"`
		ReceivedEventsURL string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"sender"`
}
